/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import model.User;


/**
 *
 * @author dannyjimenez
 */
public class AdminWindow extends javax.swing.JFrame {

    /**
     * Creates new form AdminWindow
     */
    private User user;
    private ImageIcon clientImage;
    private ImageIcon icon;
    
    public AdminWindow(User user) {
        initComponents();
        this.user = user;
        
        this.clientImage = new ImageIcon(this.user.getPhotoUrl());
        if (this.user.getUserTypeName().equals("admin")){
            Index.remove(myAccount);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        profilePhoto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        imageIcon = new javax.swing.JLabel();
        Index = new javax.swing.JTabbedPane();
        Dashboard = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        myAccount = new javax.swing.JPanel();
        reportingTab = new javax.swing.JTabbedPane();
        affBusinesses = new javax.swing.JPanel();
        usersReport = new javax.swing.JPanel();
        productsReport = new javax.swing.JPanel();
        pointsReport = new javax.swing.JPanel();
        affBusinessReports = new javax.swing.JTabbedPane();
        topProducts = new javax.swing.JPanel();
        offeredProducts = new javax.swing.JPanel();
        redeemedPoints = new javax.swing.JPanel();
        collectionCenterReports = new javax.swing.JTabbedPane();
        materialTypesReport = new javax.swing.JPanel();
        topUsersReport = new javax.swing.JPanel();
        redeemedPointsReport = new javax.swing.JPanel();
        stadisticReports = new javax.swing.JTabbedPane();
        usersStadistics = new javax.swing.JPanel();
        productsStadistics = new javax.swing.JPanel();
        topUsersStadistics = new javax.swing.JPanel();
        centersStadistics = new javax.swing.JPanel();
        maintainanceTab = new javax.swing.JTabbedPane();
        labelManager = new javax.swing.JPanel();
        locationManager = new javax.swing.JPanel();
        genderManager = new javax.swing.JPanel();
        AFFBusinessManager = new javax.swing.JPanel();
        CCManager = new javax.swing.JPanel();
        materialTypeManager = new javax.swing.JPanel();
        businessTypeManager = new javax.swing.JPanel();
        centerTypeManager = new javax.swing.JPanel();
        pointsManager = new javax.swing.JPanel();
        redeemPointsTab = new javax.swing.JPanel();
        recycleTab = new javax.swing.JPanel();
        infoTab = new javax.swing.JPanel();
        usersTab = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        main.setBackground(new java.awt.Color(0, 51, 102));
        main.setPreferredSize(new java.awt.Dimension(1200, 800));

        header.setBackground(new java.awt.Color(0, 51, 102));

        profilePhoto.setBackground(new java.awt.Color(255, 255, 255));
        profilePhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profilePhoto.setIcon(this.clientImage);
        profilePhoto.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText(this.user.getUsername());
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText(this.user.getUserTypeName());
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        imageIcon.setBackground(new java.awt.Color(255, 255, 255));
        imageIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageIcon.setOpaque(true);

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(profilePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addComponent(profilePhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imageIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Index.setBackground(new java.awt.Color(0, 51, 102));
        Index.setForeground(new java.awt.Color(255, 255, 255));
        Index.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        Index.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        Index.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Index.setMinimumSize(new java.awt.Dimension(62, 64));
        Index.setPreferredSize(new java.awt.Dimension(200, 200));

        Dashboard.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Welcome back " + this.user.getFirstName() + "."
        );
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout DashboardLayout = new javax.swing.GroupLayout(Dashboard);
        Dashboard.setLayout(DashboardLayout);
        DashboardLayout.setHorizontalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 987, Short.MAX_VALUE)
                .addContainerGap())
        );
        DashboardLayout.setVerticalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(647, Short.MAX_VALUE))
        );

        Index.addTab("<html><div style=\"padding: 10px;\">Dashboard<div></html>", Dashboard);

        myAccount.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout myAccountLayout = new javax.swing.GroupLayout(myAccount);
        myAccount.setLayout(myAccountLayout);
        myAccountLayout.setHorizontalGroup(
            myAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        myAccountLayout.setVerticalGroup(
            myAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Index.addTab("<html><div style=\"padding: 10px\">My Account<div></html>", myAccount);

        reportingTab.setBackground(new java.awt.Color(0, 51, 102));
        reportingTab.setForeground(new java.awt.Color(255, 255, 255));
        reportingTab.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        reportingTab.setFocusable(false);
        reportingTab.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        affBusinesses.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout affBusinessesLayout = new javax.swing.GroupLayout(affBusinesses);
        affBusinesses.setLayout(affBusinessesLayout);
        affBusinessesLayout.setHorizontalGroup(
            affBusinessesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        affBusinessesLayout.setVerticalGroup(
            affBusinessesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        reportingTab.addTab("<html><div style=\"padding:10px;\" >Affiliated Businesses<div></html>", affBusinesses);

        usersReport.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout usersReportLayout = new javax.swing.GroupLayout(usersReport);
        usersReport.setLayout(usersReportLayout);
        usersReportLayout.setHorizontalGroup(
            usersReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        usersReportLayout.setVerticalGroup(
            usersReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        reportingTab.addTab("<html><div style=\"padding:10px;\" >Users Report<div></html>", usersReport);

        productsReport.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout productsReportLayout = new javax.swing.GroupLayout(productsReport);
        productsReport.setLayout(productsReportLayout);
        productsReportLayout.setHorizontalGroup(
            productsReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        productsReportLayout.setVerticalGroup(
            productsReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        reportingTab.addTab("<html><div style=\"padding:10px;\" >Product Reports<div></html>", productsReport);

        pointsReport.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pointsReportLayout = new javax.swing.GroupLayout(pointsReport);
        pointsReport.setLayout(pointsReportLayout);
        pointsReportLayout.setHorizontalGroup(
            pointsReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        pointsReportLayout.setVerticalGroup(
            pointsReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        reportingTab.addTab("<html><div style=\"padding:10px;\" >Points Report<div></html>", pointsReport);

        Index.addTab("<html><div style=\"padding: 10px;\">Reports<div></html>", reportingTab);

        affBusinessReports.setBackground(new java.awt.Color(0, 51, 102));
        affBusinessReports.setForeground(new java.awt.Color(255, 255, 255));
        affBusinessReports.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        topProducts.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout topProductsLayout = new javax.swing.GroupLayout(topProducts);
        topProducts.setLayout(topProductsLayout);
        topProductsLayout.setHorizontalGroup(
            topProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        topProductsLayout.setVerticalGroup(
            topProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        affBusinessReports.addTab("<html><div style=\"padding:10px;\" >Top Products<div></html>", topProducts);

        offeredProducts.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout offeredProductsLayout = new javax.swing.GroupLayout(offeredProducts);
        offeredProducts.setLayout(offeredProductsLayout);
        offeredProductsLayout.setHorizontalGroup(
            offeredProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        offeredProductsLayout.setVerticalGroup(
            offeredProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        affBusinessReports.addTab("<html><div style=\"padding:10px;\" >Products<div></html>", offeredProducts);

        redeemedPoints.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout redeemedPointsLayout = new javax.swing.GroupLayout(redeemedPoints);
        redeemedPoints.setLayout(redeemedPointsLayout);
        redeemedPointsLayout.setHorizontalGroup(
            redeemedPointsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        redeemedPointsLayout.setVerticalGroup(
            redeemedPointsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        affBusinessReports.addTab("<html><div style=\"padding:10px;\" >Redeemed Points<div></html>", redeemedPoints);

        Index.addTab("<html><div style=\"padding: 10px;\">Affiliated Business<div></html>", affBusinessReports);

        collectionCenterReports.setBackground(new java.awt.Color(0, 51, 102));
        collectionCenterReports.setForeground(new java.awt.Color(255, 255, 255));
        collectionCenterReports.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        materialTypesReport.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout materialTypesReportLayout = new javax.swing.GroupLayout(materialTypesReport);
        materialTypesReport.setLayout(materialTypesReportLayout);
        materialTypesReportLayout.setHorizontalGroup(
            materialTypesReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        materialTypesReportLayout.setVerticalGroup(
            materialTypesReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        collectionCenterReports.addTab("<html><div style=\"padding:10px;\" >Material Types<div></html>", materialTypesReport);

        topUsersReport.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout topUsersReportLayout = new javax.swing.GroupLayout(topUsersReport);
        topUsersReport.setLayout(topUsersReportLayout);
        topUsersReportLayout.setHorizontalGroup(
            topUsersReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        topUsersReportLayout.setVerticalGroup(
            topUsersReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        collectionCenterReports.addTab("<html><div style=\"padding:10px;\" >Top Users<div></html>", topUsersReport);

        redeemedPointsReport.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout redeemedPointsReportLayout = new javax.swing.GroupLayout(redeemedPointsReport);
        redeemedPointsReport.setLayout(redeemedPointsReportLayout);
        redeemedPointsReportLayout.setHorizontalGroup(
            redeemedPointsReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        redeemedPointsReportLayout.setVerticalGroup(
            redeemedPointsReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        collectionCenterReports.addTab("<html><div style=\"padding:10px;\" >Redeemed Points <div></html>", redeemedPointsReport);

        Index.addTab("<html><div style=\"padding: 10px;\">Collection Centers<div></html>", collectionCenterReports);

        stadisticReports.setBackground(new java.awt.Color(0, 51, 102));
        stadisticReports.setForeground(new java.awt.Color(255, 255, 255));
        stadisticReports.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        usersStadistics.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout usersStadisticsLayout = new javax.swing.GroupLayout(usersStadistics);
        usersStadistics.setLayout(usersStadisticsLayout);
        usersStadisticsLayout.setHorizontalGroup(
            usersStadisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        usersStadisticsLayout.setVerticalGroup(
            usersStadisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        stadisticReports.addTab("<html><div style=\"padding:10px;\" >Users<div></html>", usersStadistics);

        productsStadistics.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout productsStadisticsLayout = new javax.swing.GroupLayout(productsStadistics);
        productsStadistics.setLayout(productsStadisticsLayout);
        productsStadisticsLayout.setHorizontalGroup(
            productsStadisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        productsStadisticsLayout.setVerticalGroup(
            productsStadisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        stadisticReports.addTab("<html><div style=\"padding:10px;\" >Products<div></html>", productsStadistics);

        topUsersStadistics.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout topUsersStadisticsLayout = new javax.swing.GroupLayout(topUsersStadistics);
        topUsersStadistics.setLayout(topUsersStadisticsLayout);
        topUsersStadisticsLayout.setHorizontalGroup(
            topUsersStadisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        topUsersStadisticsLayout.setVerticalGroup(
            topUsersStadisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        stadisticReports.addTab("<html><div style=\"padding:10px;\" >Top Users<div></html>", topUsersStadistics);

        centersStadistics.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout centersStadisticsLayout = new javax.swing.GroupLayout(centersStadistics);
        centersStadistics.setLayout(centersStadisticsLayout);
        centersStadisticsLayout.setHorizontalGroup(
            centersStadisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        centersStadisticsLayout.setVerticalGroup(
            centersStadisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        stadisticReports.addTab("<html><div style=\"padding:10px;\" >Collection Centers<div></html>", centersStadistics);

        Index.addTab("<html><div style=\"padding: 10px;\">Stadisticts<div></html>", stadisticReports);

        maintainanceTab.setBackground(new java.awt.Color(0, 51, 102));
        maintainanceTab.setForeground(new java.awt.Color(255, 255, 255));
        maintainanceTab.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        labelManager.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout labelManagerLayout = new javax.swing.GroupLayout(labelManager);
        labelManager.setLayout(labelManagerLayout);
        labelManagerLayout.setHorizontalGroup(
            labelManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        labelManagerLayout.setVerticalGroup(
            labelManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        maintainanceTab.addTab("tab1", labelManager);

        locationManager.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout locationManagerLayout = new javax.swing.GroupLayout(locationManager);
        locationManager.setLayout(locationManagerLayout);
        locationManagerLayout.setHorizontalGroup(
            locationManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        locationManagerLayout.setVerticalGroup(
            locationManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        maintainanceTab.addTab("tab2", locationManager);

        genderManager.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout genderManagerLayout = new javax.swing.GroupLayout(genderManager);
        genderManager.setLayout(genderManagerLayout);
        genderManagerLayout.setHorizontalGroup(
            genderManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        genderManagerLayout.setVerticalGroup(
            genderManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        maintainanceTab.addTab("tab3", genderManager);

        AFFBusinessManager.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout AFFBusinessManagerLayout = new javax.swing.GroupLayout(AFFBusinessManager);
        AFFBusinessManager.setLayout(AFFBusinessManagerLayout);
        AFFBusinessManagerLayout.setHorizontalGroup(
            AFFBusinessManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        AFFBusinessManagerLayout.setVerticalGroup(
            AFFBusinessManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        maintainanceTab.addTab("tab4", AFFBusinessManager);

        CCManager.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout CCManagerLayout = new javax.swing.GroupLayout(CCManager);
        CCManager.setLayout(CCManagerLayout);
        CCManagerLayout.setHorizontalGroup(
            CCManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        CCManagerLayout.setVerticalGroup(
            CCManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        maintainanceTab.addTab("tab5", CCManager);

        materialTypeManager.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout materialTypeManagerLayout = new javax.swing.GroupLayout(materialTypeManager);
        materialTypeManager.setLayout(materialTypeManagerLayout);
        materialTypeManagerLayout.setHorizontalGroup(
            materialTypeManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        materialTypeManagerLayout.setVerticalGroup(
            materialTypeManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        maintainanceTab.addTab("tab6", materialTypeManager);

        businessTypeManager.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout businessTypeManagerLayout = new javax.swing.GroupLayout(businessTypeManager);
        businessTypeManager.setLayout(businessTypeManagerLayout);
        businessTypeManagerLayout.setHorizontalGroup(
            businessTypeManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        businessTypeManagerLayout.setVerticalGroup(
            businessTypeManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        maintainanceTab.addTab("tab7", businessTypeManager);

        centerTypeManager.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout centerTypeManagerLayout = new javax.swing.GroupLayout(centerTypeManager);
        centerTypeManager.setLayout(centerTypeManagerLayout);
        centerTypeManagerLayout.setHorizontalGroup(
            centerTypeManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        centerTypeManagerLayout.setVerticalGroup(
            centerTypeManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        maintainanceTab.addTab("tab8", centerTypeManager);

        pointsManager.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pointsManagerLayout = new javax.swing.GroupLayout(pointsManager);
        pointsManager.setLayout(pointsManagerLayout);
        pointsManagerLayout.setHorizontalGroup(
            pointsManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        pointsManagerLayout.setVerticalGroup(
            pointsManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        maintainanceTab.addTab("tab9", pointsManager);

        Index.addTab("<html><div style=\"padding: 10px;\">Mantainance<div></html>", maintainanceTab);

        redeemPointsTab.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout redeemPointsTabLayout = new javax.swing.GroupLayout(redeemPointsTab);
        redeemPointsTab.setLayout(redeemPointsTabLayout);
        redeemPointsTabLayout.setHorizontalGroup(
            redeemPointsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        redeemPointsTabLayout.setVerticalGroup(
            redeemPointsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );

        Index.addTab("<html><div style=\"padding: 10px;\">Redeem Points<div></html>", redeemPointsTab);

        recycleTab.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout recycleTabLayout = new javax.swing.GroupLayout(recycleTab);
        recycleTab.setLayout(recycleTabLayout);
        recycleTabLayout.setHorizontalGroup(
            recycleTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        recycleTabLayout.setVerticalGroup(
            recycleTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );

        Index.addTab("<html><div style=\"padding: 10px;\">Recycle<div></html>", recycleTab);

        infoTab.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout infoTabLayout = new javax.swing.GroupLayout(infoTab);
        infoTab.setLayout(infoTabLayout);
        infoTabLayout.setHorizontalGroup(
            infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        infoTabLayout.setVerticalGroup(
            infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );

        Index.addTab("<html><div style=\"padding: 10px;\">Information<div></html>", infoTab);

        usersTab.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout usersTabLayout = new javax.swing.GroupLayout(usersTab);
        usersTab.setLayout(usersTabLayout);
        usersTabLayout.setHorizontalGroup(
            usersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        usersTabLayout.setVerticalGroup(
            usersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );

        Index.addTab("<html><div style=\"padding: 10px;\">Users<div></html>", usersTab);

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Index, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
            .addComponent(header, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Index, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AFFBusinessManager;
    private javax.swing.JPanel CCManager;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JTabbedPane Index;
    private javax.swing.JTabbedPane affBusinessReports;
    private javax.swing.JPanel affBusinesses;
    private javax.swing.JPanel businessTypeManager;
    private javax.swing.JPanel centerTypeManager;
    private javax.swing.JPanel centersStadistics;
    private javax.swing.JTabbedPane collectionCenterReports;
    private javax.swing.JPanel genderManager;
    private javax.swing.JPanel header;
    private javax.swing.JLabel imageIcon;
    private javax.swing.JPanel infoTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel labelManager;
    private javax.swing.JPanel locationManager;
    private javax.swing.JPanel main;
    private javax.swing.JTabbedPane maintainanceTab;
    private javax.swing.JPanel materialTypeManager;
    private javax.swing.JPanel materialTypesReport;
    private javax.swing.JPanel myAccount;
    private javax.swing.JPanel offeredProducts;
    private javax.swing.JPanel pointsManager;
    private javax.swing.JPanel pointsReport;
    private javax.swing.JPanel productsReport;
    private javax.swing.JPanel productsStadistics;
    private javax.swing.JLabel profilePhoto;
    private javax.swing.JPanel recycleTab;
    private javax.swing.JPanel redeemPointsTab;
    private javax.swing.JPanel redeemedPoints;
    private javax.swing.JPanel redeemedPointsReport;
    private javax.swing.JTabbedPane reportingTab;
    private javax.swing.JTabbedPane stadisticReports;
    private javax.swing.JPanel topProducts;
    private javax.swing.JPanel topUsersReport;
    private javax.swing.JPanel topUsersStadistics;
    private javax.swing.JPanel usersReport;
    private javax.swing.JPanel usersStadistics;
    private javax.swing.JPanel usersTab;
    // End of variables declaration//GEN-END:variables
}
