ALTER SESSION SET CURRENT_SCHEMA = SYSTEM;

CREATE TABLESPACE BLUE_Data
DATAFILE '/opt/oracle/oradata/ORCLCDB/BLUE_data01.dbf'
SIZE 10M
REUSE
AUTOEXTEND ON
NEXT 512K
MAXSIZE 200M;

CREATE TABLESPACE BLUE_Ind
DATAFILE '/opt/oracle/oradata/ORCLCDB/BLUE_ind01.dbf'
SIZE 10M
REUSE
AUTOEXTEND ON
NEXT 512K
MAXSIZE 200M;


CREATE USER BLUE
IDENTIFIED BY BLUE
DEFAULT TABLESPACE BLUE_DATA
QUOTA 10M ON BLUE_DATA
TEMPORARY TABLESPACE  TEMP
QUOTA 5M ON SYSTEM
QUOTA 100M ON BLUE_IND;

GRANT CONNECT TO BLUE;
GRANT CREATE TABLE TO BLUE;
GRANT CREATE SESSION TO BLUE;
GRANT CREATE VIEW TO BLUE;

COMMIT;