ALTER SESSION SET CURRENT_SCHEMA = BLUE;

-- PRIMARY KEY CREATION PART
ALTER TABLE Users
ADD CONSTRAINT PK_USERS PRIMARY KEY (id)
USING INDEX
TABLESPACE BLUE_IND PCTFREE 20
STORAGE ( INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Phones
ADD CONSTRAINT PK_PHONES PRIMARY KEY (id)
USING INDEX
TABLESPACE BLUE_IND PCTFREE 20
STORAGE ( INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Emails
ADD CONSTRAINT PK_TB_EMAILS PRIMARY KEY (id)
USING INDEX
TABLESPACE BLUE_IND PCTFREE 20
STORAGE ( INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE UserTypes
ADD CONSTRAINT PK_USER_TYPES PRIMARY KEY (id)
USING INDEX
TABLESPACE BLUE_IND PCTFREE 20
STORAGE ( INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE IdType
ADD CONSTRAINT PK_ID_TYPES PRIMARY KEY (id)
USING INDEX
TABLESPACE BLUE_IND PCTFREE 20
STORAGE ( INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Genders
ADD CONSTRAINT PK_GENDERS PRIMARY KEY (id)
USING INDEX
TABLESPACE BLUE_IND PCTFREE 20
STORAGE ( INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Labels
ADD CONSTRAINT PK_LABELS PRIMARY KEY (id)
USING INDEX
TABLESPACE BLUE_IND PCTFREE 20
STORAGE ( INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE District
ADD CONSTRAINT pk_District PRIMARY KEY (id)
USING INDEX
TABLESPACE BLUE_IND PCTFREE 20
STORAGE ( INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE City
ADD CONSTRAINT pk_City PRIMARY KEY (id)
USING INDEX
TABLESPACE BLUE_IND PCTFREE 20
STORAGE ( INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Province
ADD CONSTRAINT pk_Province PRIMARY KEY (id)
USING INDEX
TABLESPACE BLUE_IND PCTFREE 20
STORAGE ( INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Country
ADD CONSTRAINT pk_Country PRIMARY KEY (id)
USING INDEX
TABLESPACE BLUE_IND PCTFREE 20
STORAGE ( INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Product
ADD CONSTRAINT pk_Product PRIMARY KEY (id)
USING INDEX
TABLESPACE BLUE_IND PCTFREE 20
STORAGE ( INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE ProductXUser
ADD CONSTRAINT pk_ProductXUser PRIMARY KEY (id)
USING INDEX
TABLESPACE BLUE_IND PCTFREE 20
STORAGE ( INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE PointsConvertion
ADD CONSTRAINT pk_PointsConvertion PRIMARY KEY (id)
USING INDEX
TABLESPACE BLUE_IND PCTFREE 20
STORAGE ( INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Currency
ADD CONSTRAINT pk_Currency PRIMARY KEY (id)
USING INDEX
TABLESPACE BLUE_IND PCTFREE 20
STORAGE ( INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE UserXCollectionCenter
ADD CONSTRAINT pk_UXC PRIMARY KEY (id)
USING INDEX
TABLESPACE BLUE_IND PCTFREE 20
STORAGE ( INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE MaterialTypeXCollectionCenter
ADD CONSTRAINT pk_TMXCenter PRIMARY KEY (id)
USING INDEX
TABLESPACE BLUE_IND PCTFREE 20
STORAGE ( INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE MaterialType
ADD CONSTRAINT pk_MaterialType PRIMARY KEY (id)
USING INDEX
TABLESPACE BLUE_IND PCTFREE 20
STORAGE ( INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE CenterType
ADD CONSTRAINT pk_CenterType PRIMARY KEY (id)
USING INDEX
TABLESPACE AD_IND PCTFREE 20
STORAGE ( INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE CollectionCenter
ADD CONSTRAINT pk_AutorizedEntityid_C PRIMARY KEY (AutorizedEntityid)
USING INDEX
TABLESPACE AD_IND PCTFREE 20
STORAGE ( INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE BusinessType
ADD CONSTRAINT pk_BusinessType PRIMARY KEY (id)
USING INDEX
TABLESPACE AD_IND PCTFREE 20
STORAGE ( INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE AffiliatedBusiness
ADD CONSTRAINT pk_AutorizedEntityid PRIMARY KEY (AutorizedEntityid)
USING INDEX
TABLESPACE AD_IND PCTFREE 20
STORAGE ( INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE AutorizedEntity
ADD CONSTRAINT pk_AutorizedEntity PRIMARY KEY (id)
USING INDEX
TABLESPACE AD_IND PCTFREE 20
STORAGE ( INITIAL 10K NEXT 10K PCTINCREASE 0);

-- FOREIGN KEY CREATION

-- TABLE USERS: ID TYPE ID
ALTER TABLE USERS
ADD CONSTRAINT FK_TB_USERS_ID_TYPE_ID FOREIGN KEY (ID_TYPEID) REFERENCES IDTYPE(id);
-- TABLE USERS: USER TYPE ID
ALTER TABLE USERS
ADD CONSTRAINT FK_TB_USERS_USER_TYPE_ID FOREIGN KEY (USERTYPEID) REFERENCES USERTYPES(id);
-- TABLE USERS: GENDER ID
ALTER TABLE USERS
ADD CONSTRAINT FK_TB_USERS_GENDER_ID FOREIGN KEY (GENDERID) REFERENCES GENDERS(id);
-- TABLE USERS: DISTRICT ID
ALTER TABLE USERS
ADD CONSTRAINT FK_TB_USERS_DISTRICT_ID FOREIGN KEY (DISTRICTID) REFERENCES DISTRICT(id);

-- TABLE PHONES: LABEL ID
ALTER TABLE PHONES
ADD CONSTRAINT FK_TB_PHONES_LABEL_ID FOREIGN KEY (LABELID) REFERENCES LABELS(id);
-- TABLE PHONES: LABEL ID
ALTER TABLE PHONES
ADD CONSTRAINT FK_TB_PHONES_USER_ID FOREIGN KEY (USERID) REFERENCES USERS(id);


-- TABLE EMAILS: LABEL ID
ALTER TABLE EMAILS
ADD CONSTRAINT FK_TB_EMAILS_LABEL_ID FOREIGN KEY (USERID) REFERENCES LABELS(id);
-- TABLE EMAILS: LABEL ID
ALTER TABLE EMAILS
ADD CONSTRAINT FK_TB_EMAILS_USER_ID FOREIGN KEY (USERID) REFERENCES USERS(id);

ALTER TABLE PointsConvertion
ADD CONSTRAINT fk_PointsConvertion_CurrencyId FOREIGN KEY (CurrencyId) REFERENCES Currency(Id);

ALTER TABLE PointsConvertion
ADD CONSTRAINT fk_PointsConvertion_MaterialTypeId FOREIGN KEY (MaterialTypeId) REFERENCES MaterialType(Id);

ALTER TABLE ProductXUser
ADD CONSTRAINT fk_ProductXUser_userId FOREIGN KEY (userId) REFERENCES users(Id);

ALTER TABLE ProductXUser
ADD CONSTRAINT fk_ProductXUser_productId FOREIGN KEY (productId) REFERENCES product(Id);

ALTER TABLE Product
ADD CONSTRAINT fk_Product_authorizedEntityId FOREIGN KEY (authorizedEntityId) REFERENCES AFFILIATEDBUSINESS(AUTORIZEDENTITYID);

ALTER TABLE Province
ADD CONSTRAINT fk_Province_CountryId FOREIGN KEY (CountryId) REFERENCES Country(Id);

ALTER TABLE City
ADD CONSTRAINT fk_City_ProvinceId FOREIGN KEY (ProvinceId) REFERENCES Province(Id);

ALTER TABLE District
ADD CONSTRAINT fk_District_CityId FOREIGN KEY (CityId) REFERENCES City(Id);

ALTER TABLE AutorizedEntity
ADD CONSTRAINT fk_AutorizedEntity_DistrictId FOREIGN KEY (DistrictId) REFERENCES District(id);

ALTER TABLE AffiliatedBusiness
ADD CONSTRAINT fk_AfBusiness_AEid FOREIGN KEY (AutorizedEntityid) REFERENCES AutorizedEntity(id);

ALTER TABLE AffiliatedBusiness
ADD CONSTRAINT fk_AfBusiness_BusinessType FOREIGN KEY (BusinessTypeid) REFERENCES BusinessType(id);

ALTER TABLE CollectionCenter
ADD CONSTRAINT fk_CollectionC_AEid FOREIGN KEY (AutorizedEntityid) REFERENCES AutorizedEntity(id);

ALTER TABLE CollectionCenter
ADD CONSTRAINT fk_CollectionC_CenterType FOREIGN KEY (centerTypeid) REFERENCES CenterType(id);

ALTER TABLE MaterialTypeXCollectionCenter
ADD CONSTRAINT fk_AutorizedEntity_TMXCenter FOREIGN KEY (AutorizedEntityid) REFERENCES CollectionCenter(AutorizedEntityid);

ALTER TABLE MaterialTypeXCollectionCenter
ADD CONSTRAINT fk_TMXCenter_MaterialType FOREIGN KEY (materialTypeid) REFERENCES MaterialType(id);

ALTER TABLE UserXCollectionCenter
ADD CONSTRAINT fk_UXC_CollectionC FOREIGN KEY (CollectionCenter) REFERENCES CollectionCenter(AutorizedEntityid);

ALTER TABLE UserXCollectionCenter
ADD CONSTRAINT fk_UXC_PointsC FOREIGN KEY (pointsConvertionKey) REFERENCES PointsConvertion(id);

ALTER TABLE UserXCollectionCenter
ADD CONSTRAINT fk_UXC_userId FOREIGN KEY (userId) REFERENCES Users(id);



COMMIT;